import type { PhrasesData, VocabularyData } from "./types"

export const INITIAL_VOCABULARY_DATA: VocabularyData = {
  Essential_Greetings: {
    English: [
      "Hello",
      "Goodbye",
      "Thank you",
      "Please",
      "Excuse me",
      "Good morning",
      "Good afternoon",
      "Good night",
      "How are you?",
      "I'm fine",
    ],
    Spanish: [
      "Hola",
      "Adiós",
      "Gracias",
      "Por favor",
      "Con permiso",
      "Buenos días",
      "Buenas tardes",
      "Buenas noches",
      "¿Cómo estás?",
      "Estoy bien",
    ],
    Pronunciation: [
      "OH-lah",
      "ah-DYOHS",
      "GRAH-thyahs",
      "por fah-VOR",
      "kon per-MEE-so",
      "BWAY-nos DEE-ahs",
      "BWAY-nas TAR-des",
      "BWAY-nas NO-ches",
      "KOH-moh ehs-TAHS",
      "ehs-TOY bee-EHN",
    ],
  },
  Family_Members: {
    English: [
      "Mother/Mom",
      "Father/Dad",
      "Sister",
      "Brother",
      "Grandmother",
      "Grandfather",
      "Aunt",
      "Uncle",
      "Cousin",
      "Baby",
    ],
    Spanish: [
      "Madre/Mamá",
      "Padre/Papá",
      "Hermana",
      "Hermano",
      "Abuela",
      "Abuelo",
      "Tía",
      "Tío",
      "Primo/Prima",
      "Bebé",
    ],
    Pronunciation: [
      "MAH-dreh/mah-MAH",
      "PAH-dreh/pah-PAH",
      "er-MAH-nah",
      "er-MAH-no",
      "ah-BWAY-lah",
      "ah-BWAY-lo",
      "TEE-ah",
      "TEE-oh",
      "PREE-mo/PREE-mah",
      "beh-BEH",
    ],
  },
  Spatial_Words: {
    English: [
      "On/On top of",
      "Under",
      "Next to",
      "Behind",
      "In front of",
      "Inside",
      "Outside",
      "Between",
      "Above",
      "Below",
    ],
    Spanish: [
      "Encima de/Sobre",
      "Debajo de",
      "Al lado de",
      "Detrás de",
      "Delante de",
      "Dentro de",
      "Fuera de",
      "Entre",
      "Arriba de",
      "Abajo de",
    ],
    Pronunciation: [
      "en-SEE-mah deh",
      "deh-BAH-ho deh",
      "ahl LAH-do deh",
      "deh-TRAHS deh",
      "deh-LAHN-teh deh",
      "DEN-tro deh",
      "FWAY-rah deh",
      "EN-treh",
      "ah-REE-bah deh",
      "ah-BAH-ho deh",
    ],
  },
  Feelings_Emotions: {
    English: ["Happy", "Sad", "Angry", "Tired", "Hungry", "Thirsty", "Excited", "Scared", "Hot", "Cold"],
    Spanish: [
      "Feliz/Contento",
      "Triste",
      "Enojado",
      "Cansado",
      "Hambriento",
      "Sediento",
      "Emocionado",
      "Asustado",
      "Caliente",
      "Frío",
    ],
    Pronunciation: [
      "feh-LEES/kon-TEN-to",
      "TREES-teh",
      "eh-no-HAH-do",
      "kan-SAH-do",
      "am-bree-EN-to",
      "seh-dee-EN-to",
      "eh-mo-see-o-NAH-do",
      "ah-soos-TAH-do",
      "ka-lee-EN-teh",
      "FREE-o",
    ],
  },
  Body_Parts: {
    English: ["Head", "Hair", "Eyes", "Nose", "Mouth", "Hands", "Feet", "Arms", "Legs", "Back"],
    Spanish: ["Cabeza", "Pelo", "Ojos", "Nariz", "Boca", "Manos", "Pies", "Brazos", "Piernas", "Espalda"],
    Pronunciation: [
      "ka-BEH-sah",
      "PEH-lo",
      "OH-hos",
      "nah-REES",
      "BOH-ka",
      "MAH-nos",
      "pee-EHS",
      "BRAH-sos",
      "pee-ER-nas",
      "ehs-PAHL-da",
    ],
  },
  Colors: {
    English: ["Red", "Blue", "Yellow", "Green", "Black", "White", "Pink", "Orange", "Purple", "Brown"],
    Spanish: ["Rojo", "Azul", "Amarillo", "Verde", "Negro", "Blanco", "Rosa", "Naranja", "Morado", "Marrón"],
    Pronunciation: [
      "ROH-ho",
      "ah-SOOL",
      "ah-mah-REE-yo",
      "VER-deh",
      "NEH-gro",
      "BLAHN-ko",
      "ROH-sa",
      "nah-RAHN-ha",
      "mo-RAH-do",
      "mah-ROHN",
    ],
  },
  Food_Basics: {
    English: ["Water", "Milk", "Bread", "Apple", "Banana", "Chicken", "Rice", "Beans", "Cheese", "Egg"],
    Spanish: ["Agua", "Leche", "Pan", "Manzana", "Plátano", "Pollo", "Arroz", "Frijoles", "Queso", "Huevo"],
    Pronunciation: [
      "AH-gwa",
      "LEH-cheh",
      "pahn",
      "man-SAH-na",
      "PLAH-ta-no",
      "POH-yo",
      "ah-ROHS",
      "free-HOH-les",
      "KEH-so",
      "WAY-vo",
    ],
  },
  Daily_Actions: {
    English: [
      "Wake up",
      "Get dressed",
      "Eat breakfast",
      "Go to school",
      "Play",
      "Take a bath",
      "Brush teeth",
      "Go to bed",
      "Walk",
      "Run",
    ],
    Spanish: [
      "Despertarse",
      "Vestirse",
      "Desayunar",
      "Ir a la escuela",
      "Jugar",
      "Bañarse",
      "Lavarse los dientes",
      "Acostarse",
      "Caminar",
      "Correr",
    ],
    Pronunciation: [
      "des-per-TAR-seh",
      "ves-TEER-seh",
      "deh-sah-yu-NAHR",
      "eer ah lah ehs-KWAY-lah",
      "hu-GAHR",
      "bah-NYAR-seh",
      "la-VAR-seh los dee-EN-tes",
      "ah-kos-TAR-seh",
      "ka-mee-NAHR",
      "ko-RRER",
    ],
  },
}

export const INITIAL_PHRASES_DATA: VocabularyData = {
  Morning: {
    English: [
      "Good morning!",
      "Time to wake up",
      "Get dressed",
      "Let's eat breakfast",
      "Brush your teeth",
      "Where are your shoes?",
      "Ready to go?",
      "Have a great day!",
    ],
    Spanish: [
      "¡Buenos días!",
      "Hora de levantarse",
      "Vístete",
      "Vamos a desayunar",
      "Lávate los dientes",
      "¿Dónde están tus zapatos?",
      "¿Listo para ir?",
      "¡Que tengas un buen día!",
    ],
    Pronunciation: [
      "BWAY-nos DEE-ahs",
      "OH-rah deh leh-van-TAR-seh",
      "VEES-teh-teh",
      "VAH-mos ah deh-sah-yu-NAHR",
      "LAH-va-teh los dee-EN-tes",
      "DOHN-deh ehs-TAHN toos sah-PAH-tos",
      "LEES-to PAH-rah eer",
      "keh TEN-gahs oon bwen DEE-ah",
    ],
  },
  Meals: {
    English: [
      "Are you hungry?",
      "What do you want to eat?",
      "Sit down please",
      "More water?",
      "How does it taste?",
      "Finish your food",
      "May I have more?",
      "I'm full",
    ],
    Spanish: [
      "¿Tienes hambre?",
      "¿Qué quieres comer?",
      "Siéntate por favor",
      "¿Más agua?",
      "¿Cómo sabe?",
      "Termina tu comida",
      "¿Puedo tener más?",
      "Estoy lleno",
    ],
    Pronunciation: [
      "tee-EH-nes AHM-breh",
      "keh kee-EH-res ko-MEHR",
      "see-EN-ta-teh por fah-VOR",
      "mahs AH-gwa",
      "KOH-mo SAH-beh",
      "ter-MEE-nah too ko-MEE-dah",
      "PWAY-do teh-NEHR mahs",
      "ehs-TOY YEH-no",
    ],
  },
  Playtime: {
    English: [
      "Let's play!",
      "Where is the toy?",
      "Share with your sister",
      "Clean up time",
      "Be careful",
      "That's fun!",
      "Let's go outside",
      "Come here",
    ],
    Spanish: [
      "¡Vamos a jugar!",
      "¿Dónde está el juguete?",
      "Comparte con tu hermana",
      "Hora de limpiar",
      "Ten cuidado",
      "¡Qué divertido!",
      "Vamos afuera",
      "Ven acá",
    ],
    Pronunciation: [
      "VAH-mos ah hu-GAHR",
      "DOHN-deh ehs-TAH el hu-GEH-teh",
      "kom-PAR-teh kon too er-MAH-nah",
      "OH-rah del lim-pee-AHR",
      "ten kwee-DAH-do",
      "keh dee-ver-TEE-do",
      "VAH-mos ah-FWAY-rah",
      "ven ah-KAH",
    ],
  },
  Bedtime: {
    English: [
      "Time for bath",
      "Put on pajamas",
      "Brush your teeth",
      "Story time",
      "Sweet dreams",
      "Good night",
      "I love you",
      "Sleep well",
    ],
    Spanish: [
      "Hora del baño",
      "Ponte la pijama",
      "Lávate los dientes",
      "Hora del cuento",
      "Dulces sueños",
      "Buenas noches",
      "Te amo",
      "Duerme bien",
    ],
    Pronunciation: [
      "OH-rah del BAH-nyo",
      "PON-teh lah pee-HAH-mah",
      "LAH-va-teh los dee-EN-tes",
      "OH-rah del KWEN-to",
      "DOOL-ses SWAY-nyos",
      "BWAY-nas NO-ches",
      "teh AH-mo",
      "DWER-meh bee-EN",
    ],
  },
}

export const MEXICAN_EXPRESSIONS = {
  English: [
    "What's up?",
    "Really?",
    "Cool/Awesome",
    "Right now",
    "How's it going?",
    "To chat/talk",
    "Kid/Child",
    "Wow!",
  ],
  Spanish: ["¿Qué onda?", "¿Neta?", "Qué padre", "Ahorita", "¿Cómo te va?", "Platicar", "Chamaco", "¡Híjole!"],
  Usage: [
    "Very informal greeting",
    "Informal way to say really",
    "Family-friendly way to say cool",
    "Can mean now or later",
    "More natural than ¿Cómo estás?",
    "More common than hablar in Mexico",
    "Informal way to say kid",
    "Expression of surprise",
  ],
}

export const PARENT_TIPS = [
  "Start with 5-10 words per week and build gradually",
  "Use Spanish during daily routines like meals and bedtime",
  "Don't worry about perfect pronunciation - consistency matters more",
  "Celebrate any attempt at Spanish with praise",
  "Make it fun with songs, games, and positive reinforcement",
  "Connect Spanish to activities your children already enjoy",
  "Be patient - language acquisition takes time",
  "Model correct usage instead of correcting mistakes directly",
]

export const STORAGE_KEYS = {
  VOCAB_DATA: "vocabularyData",
  PHRASES_DATA: "phrasesData",
  DAILY_STATS: "dailyStats",
  THEME: "theme",
  CHAT_API_ENDPOINT: "chatApiEndpoint",
  CHAT_MODEL_NAME: "chatModelName",
} as const
